[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmds = ["caddy run --config /assets/Caddyfile --adapter caddyfile"]

[start]
cmd = "caddy run --config /assets/Caddyfile --adapter caddyfile"
